/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.haizhi.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-08-09")
public class KkConf implements org.apache.thrift.TBase<KkConf, KkConf._Fields>, java.io.Serializable, Cloneable, Comparable<KkConf> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("KkConf");

  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("Status", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField THRESHHOLD_FIELD_DESC = new org.apache.thrift.protocol.TField("Threshhold", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField REQUEST_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("RequestTime", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField REPEAT_TIMES_FIELD_DESC = new org.apache.thrift.protocol.TField("RepeatTimes", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new KkConfStandardSchemeFactory());
    schemes.put(TupleScheme.class, new KkConfTupleSchemeFactory());
  }

  public int Status; // required
  public int Threshhold; // required
  public int RequestTime; // required
  public int RepeatTimes; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STATUS((short)1, "Status"),
    THRESHHOLD((short)2, "Threshhold"),
    REQUEST_TIME((short)3, "RequestTime"),
    REPEAT_TIMES((short)4, "RepeatTimes");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STATUS
          return STATUS;
        case 2: // THRESHHOLD
          return THRESHHOLD;
        case 3: // REQUEST_TIME
          return REQUEST_TIME;
        case 4: // REPEAT_TIMES
          return REPEAT_TIMES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STATUS_ISSET_ID = 0;
  private static final int __THRESHHOLD_ISSET_ID = 1;
  private static final int __REQUESTTIME_ISSET_ID = 2;
  private static final int __REPEATTIMES_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("Status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.THRESHHOLD, new org.apache.thrift.meta_data.FieldMetaData("Threshhold", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.REQUEST_TIME, new org.apache.thrift.meta_data.FieldMetaData("RequestTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.REPEAT_TIMES, new org.apache.thrift.meta_data.FieldMetaData("RepeatTimes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(KkConf.class, metaDataMap);
  }

  public KkConf() {
  }

  public KkConf(
    int Status,
    int Threshhold,
    int RequestTime,
    int RepeatTimes)
  {
    this();
    this.Status = Status;
    setStatusIsSet(true);
    this.Threshhold = Threshhold;
    setThreshholdIsSet(true);
    this.RequestTime = RequestTime;
    setRequestTimeIsSet(true);
    this.RepeatTimes = RepeatTimes;
    setRepeatTimesIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public KkConf(KkConf other) {
    __isset_bitfield = other.__isset_bitfield;
    this.Status = other.Status;
    this.Threshhold = other.Threshhold;
    this.RequestTime = other.RequestTime;
    this.RepeatTimes = other.RepeatTimes;
  }

  public KkConf deepCopy() {
    return new KkConf(this);
  }

  @Override
  public void clear() {
    setStatusIsSet(false);
    this.Status = 0;
    setThreshholdIsSet(false);
    this.Threshhold = 0;
    setRequestTimeIsSet(false);
    this.RequestTime = 0;
    setRepeatTimesIsSet(false);
    this.RepeatTimes = 0;
  }

  public int getStatus() {
    return this.Status;
  }

  public KkConf setStatus(int Status) {
    this.Status = Status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  /** Returns true if field Status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return EncodingUtils.testBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STATUS_ISSET_ID, value);
  }

  public int getThreshhold() {
    return this.Threshhold;
  }

  public KkConf setThreshhold(int Threshhold) {
    this.Threshhold = Threshhold;
    setThreshholdIsSet(true);
    return this;
  }

  public void unsetThreshhold() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __THRESHHOLD_ISSET_ID);
  }

  /** Returns true if field Threshhold is set (has been assigned a value) and false otherwise */
  public boolean isSetThreshhold() {
    return EncodingUtils.testBit(__isset_bitfield, __THRESHHOLD_ISSET_ID);
  }

  public void setThreshholdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __THRESHHOLD_ISSET_ID, value);
  }

  public int getRequestTime() {
    return this.RequestTime;
  }

  public KkConf setRequestTime(int RequestTime) {
    this.RequestTime = RequestTime;
    setRequestTimeIsSet(true);
    return this;
  }

  public void unsetRequestTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REQUESTTIME_ISSET_ID);
  }

  /** Returns true if field RequestTime is set (has been assigned a value) and false otherwise */
  public boolean isSetRequestTime() {
    return EncodingUtils.testBit(__isset_bitfield, __REQUESTTIME_ISSET_ID);
  }

  public void setRequestTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REQUESTTIME_ISSET_ID, value);
  }

  public int getRepeatTimes() {
    return this.RepeatTimes;
  }

  public KkConf setRepeatTimes(int RepeatTimes) {
    this.RepeatTimes = RepeatTimes;
    setRepeatTimesIsSet(true);
    return this;
  }

  public void unsetRepeatTimes() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REPEATTIMES_ISSET_ID);
  }

  /** Returns true if field RepeatTimes is set (has been assigned a value) and false otherwise */
  public boolean isSetRepeatTimes() {
    return EncodingUtils.testBit(__isset_bitfield, __REPEATTIMES_ISSET_ID);
  }

  public void setRepeatTimesIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REPEATTIMES_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Integer)value);
      }
      break;

    case THRESHHOLD:
      if (value == null) {
        unsetThreshhold();
      } else {
        setThreshhold((Integer)value);
      }
      break;

    case REQUEST_TIME:
      if (value == null) {
        unsetRequestTime();
      } else {
        setRequestTime((Integer)value);
      }
      break;

    case REPEAT_TIMES:
      if (value == null) {
        unsetRepeatTimes();
      } else {
        setRepeatTimes((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STATUS:
      return getStatus();

    case THRESHHOLD:
      return getThreshhold();

    case REQUEST_TIME:
      return getRequestTime();

    case REPEAT_TIMES:
      return getRepeatTimes();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STATUS:
      return isSetStatus();
    case THRESHHOLD:
      return isSetThreshhold();
    case REQUEST_TIME:
      return isSetRequestTime();
    case REPEAT_TIMES:
      return isSetRepeatTimes();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof KkConf)
      return this.equals((KkConf)that);
    return false;
  }

  public boolean equals(KkConf that) {
    if (that == null)
      return false;

    boolean this_present_Status = true;
    boolean that_present_Status = true;
    if (this_present_Status || that_present_Status) {
      if (!(this_present_Status && that_present_Status))
        return false;
      if (this.Status != that.Status)
        return false;
    }

    boolean this_present_Threshhold = true;
    boolean that_present_Threshhold = true;
    if (this_present_Threshhold || that_present_Threshhold) {
      if (!(this_present_Threshhold && that_present_Threshhold))
        return false;
      if (this.Threshhold != that.Threshhold)
        return false;
    }

    boolean this_present_RequestTime = true;
    boolean that_present_RequestTime = true;
    if (this_present_RequestTime || that_present_RequestTime) {
      if (!(this_present_RequestTime && that_present_RequestTime))
        return false;
      if (this.RequestTime != that.RequestTime)
        return false;
    }

    boolean this_present_RepeatTimes = true;
    boolean that_present_RepeatTimes = true;
    if (this_present_RepeatTimes || that_present_RepeatTimes) {
      if (!(this_present_RepeatTimes && that_present_RepeatTimes))
        return false;
      if (this.RepeatTimes != that.RepeatTimes)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_Status = true;
    list.add(present_Status);
    if (present_Status)
      list.add(Status);

    boolean present_Threshhold = true;
    list.add(present_Threshhold);
    if (present_Threshhold)
      list.add(Threshhold);

    boolean present_RequestTime = true;
    list.add(present_RequestTime);
    if (present_RequestTime)
      list.add(RequestTime);

    boolean present_RepeatTimes = true;
    list.add(present_RepeatTimes);
    if (present_RepeatTimes)
      list.add(RepeatTimes);

    return list.hashCode();
  }

  @Override
  public int compareTo(KkConf other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Status, other.Status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetThreshhold()).compareTo(other.isSetThreshhold());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetThreshhold()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Threshhold, other.Threshhold);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRequestTime()).compareTo(other.isSetRequestTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequestTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.RequestTime, other.RequestTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRepeatTimes()).compareTo(other.isSetRepeatTimes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRepeatTimes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.RepeatTimes, other.RepeatTimes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("KkConf(");
    boolean first = true;

    sb.append("Status:");
    sb.append(this.Status);
    first = false;
    if (!first) sb.append(", ");
    sb.append("Threshhold:");
    sb.append(this.Threshhold);
    first = false;
    if (!first) sb.append(", ");
    sb.append("RequestTime:");
    sb.append(this.RequestTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("RepeatTimes:");
    sb.append(this.RepeatTimes);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class KkConfStandardSchemeFactory implements SchemeFactory {
    public KkConfStandardScheme getScheme() {
      return new KkConfStandardScheme();
    }
  }

  private static class KkConfStandardScheme extends StandardScheme<KkConf> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, KkConf struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.Status = iprot.readI32();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // THRESHHOLD
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.Threshhold = iprot.readI32();
              struct.setThreshholdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REQUEST_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.RequestTime = iprot.readI32();
              struct.setRequestTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REPEAT_TIMES
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.RepeatTimes = iprot.readI32();
              struct.setRepeatTimesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, KkConf struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(STATUS_FIELD_DESC);
      oprot.writeI32(struct.Status);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(THRESHHOLD_FIELD_DESC);
      oprot.writeI32(struct.Threshhold);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(REQUEST_TIME_FIELD_DESC);
      oprot.writeI32(struct.RequestTime);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(REPEAT_TIMES_FIELD_DESC);
      oprot.writeI32(struct.RepeatTimes);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class KkConfTupleSchemeFactory implements SchemeFactory {
    public KkConfTupleScheme getScheme() {
      return new KkConfTupleScheme();
    }
  }

  private static class KkConfTupleScheme extends TupleScheme<KkConf> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, KkConf struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStatus()) {
        optionals.set(0);
      }
      if (struct.isSetThreshhold()) {
        optionals.set(1);
      }
      if (struct.isSetRequestTime()) {
        optionals.set(2);
      }
      if (struct.isSetRepeatTimes()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetStatus()) {
        oprot.writeI32(struct.Status);
      }
      if (struct.isSetThreshhold()) {
        oprot.writeI32(struct.Threshhold);
      }
      if (struct.isSetRequestTime()) {
        oprot.writeI32(struct.RequestTime);
      }
      if (struct.isSetRepeatTimes()) {
        oprot.writeI32(struct.RepeatTimes);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, KkConf struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.Status = iprot.readI32();
        struct.setStatusIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Threshhold = iprot.readI32();
        struct.setThreshholdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.RequestTime = iprot.readI32();
        struct.setRequestTimeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.RepeatTimes = iprot.readI32();
        struct.setRepeatTimesIsSet(true);
      }
    }
  }

}

